name: hello world
on:
  push:
    branches: [master]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-name:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world
        run: echo "Hello world"
