name: hello world
on:
  push:
    branches: [master]

jobs:
  run-name:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world
        run: echo "Hello world"
        
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: List all files
        run: |
          echo "This repo: ${{ github.repository }} contains the following files:"
          tree