name: Passing values betn steps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Writing a variable
          id: generate-value
          run: echo "My_value=Pradip" >> $GITHUB_OUTPUT

        - name: reading a variable
          run: echo "The value from above step ${{ steps.generate-value.outputs.My_value }}"

        - name: masking a value
          id: masking
          run: |
            secret_value=any-secret-value
            echo "::add-mask::$secret_value
            echo "SECRET_VALUE=$secret_value" >> GITHUB_OUTPUT

        - name: use the masked value
          run: echo "the masked value is ${{ steps.masking.outputs.SECRET_VALUE }}"
